//
//  AnalyzerViewModel.swift
//  WhatsApp Analyzer
//
//  ViewModel handling file import and analysis
//  All processing happens on-device
//

import Foundation
import SwiftUI
import UniformTypeIdentifiers

@MainActor
class AnalyzerViewModel: ObservableObject {
    @Published var analyses: [ChatAnalysis] = []
    @Published var isProcessing = false
    @Published var errorMessage: String?
    @Published var selectedAnalysis: ChatAnalysis?
    
    private let parser = WhatsAppParser()
    private let classifier = RelationshipClassifier()
    
    // Import and analyze a WhatsApp export file
    func importAndAnalyze(fileURL: URL) async {
        isProcessing = true
        errorMessage = nil
        
        do {
            // Parse messages
            let messages = try parser.parse(fileURL: fileURL)
            
            guard !messages.isEmpty else {
                errorMessage = "No messages found in file"
                isProcessing = false
                return
            }
            
            // Classify relationship
            let analysis = classifier.classify(messages: messages)
            
            // Save analysis
            analyses.append(analysis)
            selectedAnalysis = analysis
            
            // Save to local storage
            saveAnalyses()
            
        } catch {
            errorMessage = "Error parsing file: \(error.localizedDescription)"
        }
        
        isProcessing = false
    }
    
    // Load saved analyses from UserDefaults
    func loadAnalyses() {
        guard let data = UserDefaults.standard.data(forKey: "savedAnalyses"),
              let decoded = try? JSONDecoder().decode([ChatAnalysis].self, from: data) else {
            return
        }
        
        analyses = decoded
    }
    
    // Save analyses to UserDefaults
    private func saveAnalyses() {
        guard let encoded = try? JSONEncoder().encode(analyses) else { return }
        UserDefaults.standard.set(encoded, forKey: "savedAnalyses")
    }
    
    // Delete an analysis
    func deleteAnalysis(_ analysis: ChatAnalysis) {
        analyses.removeAll { $0.id == analysis.id }
        saveAnalyses()
        
        if selectedAnalysis?.id == analysis.id {
            selectedAnalysis = nil
        }
    }
    
    // Export analysis as text (for sharing)
    func exportAsText(analysis: ChatAnalysis) -> String {
        var text = """
        WhatsApp Relationship Analysis
        ==============================
        
        Relationship Type: \(analysis.relationshipType.emoji) \(analysis.relationshipType.rawValue)
        Confidence: \(analysis.confidenceLevel.rawValue) (\(analysis.confidenceScore))
        
        \(analysis.interpretation)
        
        Statistics
        ----------
        Total Messages: \(analysis.stats.totalMessages)
        Duration: \(analysis.durationDays) days
        Messages/Day: \(String(format: "%.1f", analysis.messagesPerDay))
        Participants: \(analysis.participants.joined(separator: ", "))
        
        Tone Analysis
        -------------
        Casual: \(String(format: "%.1f%%", analysis.toneAnalysis.casualPercentage))
        Formal: \(String(format: "%.1f%%", analysis.toneAnalysis.formalPercentage))
        Playful: \(String(format: "%.1f%%", analysis.toneAnalysis.playfulPercentage))
        
        Message Distribution
        --------------------
        """
        
        for (participant, count) in analysis.stats.messageCounts.sorted(by: { $0.value > $1.value }) {
            let percentage = Double(count) / Double(analysis.stats.totalMessages) * 100
            text += "\n\(participant): \(count) (\(String(format: "%.1f%%", percentage)))"
        }
        
        text += "\n\n"
        text += "Personality Profiles\n"
        text += "--------------------\n"
        
        for (participant, profile) in analysis.personalityProfiles {
            text += "\n\(participant):\n"
            text += "  • \(profile.communicationStyle)\n"
            text += "  • \(profile.responseStyle)\n"
            text += "  • \(profile.textingPattern)\n"
            text += "  • \(profile.expressionStyle)\n"
        }
        
        text += "\n\n---\nGenerated by WhatsApp Analyzer (all data processed on-device)\n"
        
        return text
    }
}
